## LA Citation Data Exploration

In [1]:
#- Import Dependences
import pandas as pd
import os

In [2]:
#-- Import CSV
path = "/Users/thefixermac/Development_Data/Workshop/DataScience_Project_3/los-angeles-parking-citations/parking-citations.csv"  



citations = pd.read_csv(path)


citations.head()

/Users/thefixermac/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
0,1103341116,2015-12-21T00:00:00,1251.0,NaN,NaN,CA,200304.0,NaN,HOND,PA,GY,13147 WELBY WAY,01521,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
1,1103700150,2015-12-21T00:00:00,1435.0,NaN,NaN,CA,201512.0,NaN,GMC,VN,WH,525 S MAIN ST,1C51,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
2,1104803000,2015-12-21T00:00:00,2055.0,NaN,NaN,CA,201503.0,NaN,NISS,PA,BK,200 WORLD WAY,2R2,2.0,8939,WHITE CURB,58.0,6439997.9,1802686.4
3,1104820732,2015-12-26T00:00:00,1515.0,NaN,NaN,CA,NaN,NaN,ACUR,PA,WH,100 WORLD WAY,2F11,2.0,000,17104h,NaN,6440041.1,1802686.2
4,1105461453,2015-09-15T00:00:00,115.0,NaN,NaN,CA,200316.0,NaN,CHEV,PA,BK,GEORGIA ST/OLYMPIC,1FB70,1.0,8069A,NO STOPPING/STANDING,93.0,99999.0,99999.0

In [4]:
#- Get Count of records
citations.shape

(9389057, 19)

In [5]:
#- Column Information
list(citations)

['Ticket number',
 'Issue Date',
 'Issue time',
 'Meter Id',
 'Marked Time',
 'RP State Plate',
 'Plate Expiry Date',
 'VIN',
 'Make',
 'Body Style',
 'Color',
 'Location',
 'Route',
 'Agency',
 'Violation code',
 'Violation Description',
 'Fine amount',
 'Latitude',
 'Longitude']

In [6]:
#-- Get Unique values for meter
meterUniqueValues = citations['Meter Id'].unique()

meterUniqueValues

array([nan, 'WF55', 'WF54', ..., 'Y092', 'Y079', 'Y068A'], dtype=object)

In [7]:
len(meterUniqueValues)

38003

In [8]:
#-- Get Counts of unique vlaues
meterUniqueCounts = citations['Meter Id'].value_counts()

meterUniqueCounts

37        49660
51        32652
53        32605
13        29006
49        28953
64        25888
30        24460
96        21581
36        20709
12        16951
34        15832
46        15263
41        14365
23        13527
26         9965
80         9888
40         9866
15         9756
45         9182
25         8971
81         8825
101        8775
227        8283
31         8159
132        8083
191        6955
537        6824
57         6596
3          6253
99         5564
          ...
CC1133        1
ED751         1
SO658         1
2494          1
SEC3C         1
D48           1
WW2121        1
MD56          1
1171          1
S077          1
VW1623        1
128B          1
CV1223        1
HO722         1
6626          1
VW67          1
WA93          1
464B          1
VH117         1
WW2028        1
23R81         1
RA150         1
LT484         1
WV1141        1
WW2226        1
1935          1
CB4172        1
L1247         1
WW2244        1
D85           1
Name: Meter Id, Length: 38002, dtype: int64

In [10]:
#-- Filter for individual Meter
subset_df = citations.loc[(citations["Meter Id"] == '37'), :]

subset_df.head()

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
1627,4272821663,2015-12-30T00:00:00,1917.0,37,NaN,CA,6.0,NaN,JEEP,PA,BK,1524 COURTNEY AVE,00401,54.0,80.58L,PREFERENTIAL PARKING,68.0,6453527.9,1858498.6
1628,4272821674,2015-12-30T00:00:00,1925.0,37,NaN,CA,NaN,NaN,MNNI,PA,BL,1515 COURTNEY AVE,00401,54.0,80.58L,PREFERENTIAL PARKING,68.0,6453527.9,1858343.3
1629,4272821685,2015-12-30T00:00:00,1930.0,37,NaN,CA,3.0,NaN,TSMR,PA,BK,1632 COURTNEY AVE,00401,54.0,80.58L,PREFERENTIAL PARKING,68.0,99999.0,99999.0
3474,4273524345,2015-12-30T00:00:00,1853.0,37,NaN,CA,201608.0,NaN,TOYT,PA,BK,1601 NORTH SYCAMORE AVENUE,00447,54.0,80.58L,PREFERENTIAL PARKING,68.0,6457731.4,1859071.7
4830,4273805373,2015-12-30T00:00:00,2.0,37,NaN,CA,201606.0,NaN,TOYT,PA,WT,1660 SYCAMORE AVE N,00402,54.0,80.58L,PREFERENTIAL PARKING,68.0,6457731.2,1859340.0

In [12]:
subset_df.shape

(49660, 19)

In [11]:
subsetUniqueCounts = subset_df["Location"].value_counts()

subsetUniqueCounts

7000 HAWTHORN AVE                 3956
1665 SYCAMORE AVE N               2338
1600 ORANGE DR N                  2109
1601 ORANGE DR N                  2024
1600 NORTH ORANGE DRIVE           1914
1633 ORANGE DR N                  1588
1600 ORANGE DR                    1336
1633 NORTH ORANGE DRIVE           1231
7000 HAWTHORN AVENUE              1140
7040 HAWTHORN AVE                 1106
7024 HAWTHORN AVE                 1098
1664 SYCAMORE AVE N               1056
7036 HAWTHORN AVE                 1008
1601 NORTH ORANGE DRIVE            881
1665 NORTH SYCAMORE AVENUE         753
1666 SYCAMORE AVE N                731
7044 HAWTHORN AVE                  673
1645 ORANGE DR N                   569
7000 W HAWTHORN AVE                497
7018 HAWTHORN AVE                  478
1665 SYCAMORE AVE                  475
7036 HAWTHORN AVENUE               457
1635 ORANGE DR N                   411
1631 ORANGE DR N                   406
1660 SYCAMORE AVE N                387
7024 HAWTHORN AVENUE               371
1600 SYCAMORE AVE N                359
7032 HAWTHORN AVE                  347
1664 NORTH SYCAMORE AVENUE         325
7040 HAWTHORN AVENUE               325
                                  ...
1620 LAUREL AVE                      1
1640 COURTNEY ST                     1
1625 SYCAMORE AVE N                  1
1601 NORTH LAUREL AVENUE             1
7000 DE LONGPRE AVE                  1
1534 FAIRFAX AVE N                   1
1632 N SIERRA BONITA                 1
1551 NORTH ORANGE GROVE AVENUE       1
1620 FAIRFAX AVE                     1
7036 HAWTHONE                        1
1565 ORANGE DR N                     1
1523 MCCADDEN PL N                   1
7521 HAWTHORN AVE                    1
1324 ORANGE DR N                     1
1545 COURTNEY AVENUE                 1
1631 LAUREL AVE N                    1
1633 OGDEN DR N                      1
1640 CURSON AVE N                    1
7586 DE LONGPRE AVE                  1
1555 NORTH OGDEN DRIVE               1
1619 FAIRFAX AVE                     1
1646 STANLEY AVE N                   1
1624 LAUREL AVE N                    1
1509 ORANGE GROVE AVE                1
1545 STANLEY AV N                    1
1764 LAS PALMAS AVE N                1
1540 N LAUREL AVE                    1
1004 NORTH HUDSON AVENUE             1
1530 NORTH ORANGE DRIVE              1
1614 GENESEE AVE N                   1
Name: Location, Length: 2881, dtype: int64

In [14]:
subsetViolationCounts = subset_df['Violation Description'].value_counts()

subsetViolationCounts

PREFERENTIAL PARKING    49379
PREF PARKING              195
OVNIGHT PRK W/OUT PE       83
OVERNIGHT PARKING           2
5204                        1
Name: Violation Description, dtype: int64

In [15]:
#-- Meter: Use Marked Time
markedTimeUniqueCounts = citations['Marked Time'].value_counts()

markedTimeUniqueCounts

800.0     15915
900.0      4719
1000.0     4717
1100.0     4647
830.0      3954
930.0      3939
1130.0     3595
1030.0     3517
1110.0     3190
1115.0     3009
1040.0     2919
1050.0     2902
1055.0     2866
1045.0     2863
1020.0     2802
945.0      2778
815.0      2746
820.0      2720
940.0      2692
1145.0     2665
805.0      2664
1200.0     2613
1015.0     2601
1120.0     2595
840.0      2552
955.0      2538
950.0      2509
920.0      2495
1105.0     2492
1010.0     2482
          ...
652.0         1
1807.0        1
1809.0        1
2258.0        1
136.0         1
714.0         1
2256.0        1
1812.0        1
2253.0        1
201.0         1
202.0         1
617.0         1
223.0         1
234.0         1
231.0         1
532.0         1
536.0         1
537.0         1
538.0         1
541.0         1
543.0         1
206.0         1
554.0         1
557.0         1
558.0         1
216.0         1
1731.0        1
2313.0        1
2312.0        1
1857.0        1
Name: Marked Time, Length: 1232, dtype: int64

In [16]:
#-- Violation Code: 88.13B+

violationCodeSubset_df = citations.loc[(citations["Violation code"] == '88.13B+'), :]

violationCodeSubset_df.head(20)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
530,4270903991,2015-12-30T00:00:00,807.0,WF192,NaN,CA,201605.0,NaN,AUDI,PA,GY,8330 3RD ST W,00451,54.0,88.13B+,METER EXP.,63.0,6449295.9,1849076.0
531,4270904002,2015-12-30T00:00:00,815.0,BF430,NaN,CA,201609.0,NaN,FIAT,PA,RD,8000 BEVERLY BL,00451,54.0,88.13B+,METER EXP.,63.0,6451529.2,1850273.5
551,4271419121,2015-12-30T00:00:00,1220.0,HO6630,NaN,CA,201610.0,NaN,MNNI,PA,BN,1600 VINE ST N,496R1,54.0,88.13B+,METER EXP.,63.0,6462771.4,1858859.1
552,4271419132,2015-12-30T00:00:00,1223.0,HO6632,NaN,CA,201607.0,NaN,HOND,PA,GY,1610 VINE ST N,496R1,54.0,88.13B+,METER EXP.,63.0,6462771.2,1858927.1
558,4271419191,2015-12-30T00:00:00,1244.0,HO966,NaN,CA,201604.0,NaN,FORD,VN,WT,1737 WHITLEY AV,496R1,54.0,88.13B+,METER EXP.,63.0,6460757.0,1859763.7
560,4271419213,2015-12-30T00:00:00,1300.0,HO133,NaN,CA,201602.0,NaN,TOYT,PA,SL,1645 WILCOX AV,496R1,54.0,88.13B+,METER EXP.,63.0,6461453.8,1857811.6
561,4271419224,2015-12-30T00:00:00,1454.0,L233,NaN,TX,201605.0,NaN,VOLK,PA,GY,613 LARCHMONT BL N,496R1,54.0,88.13B+,METER EXP.,63.0,6463661.2,1852404.1
571,4271459872,2015-12-30T00:00:00,1747.0,LT72,NaN,CA,201604.0,NaN,KIA,PA,WT,75 2ND ST E,00635,56.0,88.13B+,METER EXP.,63.0,99999.0,99999.0
572,4271459883,2015-12-30T00:00:00,1759.0,CC1235,NaN,CA,201609.0,NaN,VOLK,PA,SL,200 LOS ANGELES ST S,00635,56.0,88.13B+,METER EXP.,63.0,6487954.4,1840766.7
573,4271459894,2015-12-30T00:00:00,1815.0,CB3168,NaN,CA,201609.0,NaN,INFI,PA,BK,500 7TH ST W,00635,56.0,88.13B+,METER EXP.,63.0,6484260.8,1839439.6
665,4271891783,2015-12-30T00:00:00,1255.0,SW235,NaN,CA,NaN,NaN,BMW,PA,SL,5101 MELROSE AV,57V,57.0,88.13B+,METER EXP.,63.0,99999.0,99999.0
669,4271978745,2015-12-30T00:00:00,1108.0,V6127,NaN,CA,201610.0,NaN,FORD,PA,WT,29 WINDWARD AVE E,00111,51.0,88.13B+,METER EXP.,63.0,6418243.5,1818046.6
670,4271978756,2015-12-30T00:00:00,1116.0,V27610,NaN,CA,201602.0,NaN,JEEP,PA,MR,1608 PACIFIC AVE S,00111,51.0,88.13B+,METER EXP.,63.0,6418525.8,1818220.6
671,4271978760,2015-12-30T00:00:00,1122.0,V117,NaN,CA,201603.0,NaN,CHEC,TK,OT,1300 MAIN ST,00111,51.0,88.13B+,METER EXP.,63.0,6418478.2,1818975.3
672,4271978771,2015-12-30T00:00:00,1131.0,V27610,NaN,CA,201611.0,NaN,JEEP,PA,RD,1608 PACIFIC AVE S,00111,51.0,88.13B+,METER EXP.,63.0,6418525.8,1818220.6
673,4271978793,2015-12-30T00:00:00,1140.0,V6125,NaN,CA,201607.0,NaN,TOYT,PA,WT,61 WINDWARD AVE E,00111,51.0,88.13B+,METER EXP.,63.0,6418361.5,1818132.4
674,4271978804,2015-12-30T00:00:00,1151.0,V74,NaN,CA,201607.0,NaN,BMW,PA,BL,100 VENICE WAY,00111,51.0,88.13B+,METER EXP.,63.0,6418576.8,1818157.1
676,4271978826,2015-12-30T00:00:00,1154.0,V102,NaN,PA,201603.0,NaN,BMW,PA,WT,1700 MAIN ST,00111,51.0,88.13B+,METER EXP.,63.0,6418937.4,1818226.5
677,4271978830,2015-12-30T00:00:00,1159.0,V6123,NaN,CA,NaN,NaN,KIA,PA,SL,121 WINDWARD AVE E,00111,51.0,88.13B+,METER EXP.,63.0,6418613.3,1818315.2
678,4271978841,2015-12-30T00:00:00,1207.0,V166,NaN,AZ,NaN,NaN,JEEP,TK,WT,1401 MAIN ST,00111,51.0,88.13B+,METER EXP.,63.0,6418563.1,1818845.7

In [17]:
violationCodeSubset_df.shape

(1620587, 19)

In [18]:
violationCodeSubset_df['Meter Id'].value_counts()

WP8204     2686
V27610     2296
WP8202     1689
V6125      1688
V6128      1648
V6124      1384
WP8205     1225
WP8208     1135
WP8203     1125
WP8206     1098
V6126       931
WP8201      877
L16940      872
V6103       866
V6104       864
BW101       652
V6127       597
VN685A      589
V6120       586
V6105       585
V6106       537
GA22        518
V6123       507
GA22A       502
CB156       488
CB2189      482
V77         481
CB2547      471
VN687       466
CB2546      465
           ...
LC266A        1
CB92          1
MM24          1
WU106         1
WN74          1
WA1164        1
LC263         1
VM129         1
P2            1
ED468         1
PB294         1
C47           1
CB1066A       1
CB597A        1
LH297         1
SO389         1
TZ359         1
EN702         1
WF37          1
CC266         1
CC951A        1
SO640         1
WW1522        1
VW123         1
WW1008        1
WH477         1
VN112         1
CB4106        1
SO584         1
WW2383        1
Name: Meter Id, Length: 36504, dtype: int64

In [19]:
#-- Filter for individual Meter
subsetMeter_df = citations.loc[(citations["Meter Id"] == 'WP8204'), :]

subsetMeter_df.head(30)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
1747,4272935251,2015-12-30T00:00:00,1633.0,WP8204,NaN,CA,201512.0,NaN,HYUN,PA,RD,20 WASHINGTON BLVD E,00108,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
1748,4272935262,2015-12-30T00:00:00,1649.0,WP8204,NaN,CA,201606.0,NaN,GMC,PU,WT,20 WASHINGTON BLVD E,00108,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
1762,4272935424,2015-12-30T00:00:00,1949.0,WP8204,NaN,CA,201608.0,NaN,LEXS,PA,BK,20 WASHINGTON BLVD E,00108,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
2110,4273114731,2015-12-30T00:00:00,1728.0,WP8204,NaN,CA,201603.0,NaN,FORD,PA,GY,20 WASHINGTON BLVD E,00111,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
5277,4273892932,2015-12-30T00:00:00,1331.0,WP8204,NaN,CA,201608.0,NaN,AUDI,PA,GY,20 WASHINGTON BLVD E,00131,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
5278,4273892943,2015-12-30T00:00:00,1332.0,WP8204,NaN,CA,201611.0,NaN,CHEV,PA,BK,20 WASHINGTON BLVD E,00131,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
5279,4273892954,2015-12-30T00:00:00,1333.0,WP8204,NaN,CA,201610.0,NaN,MAZD,PA,BK,20 WASHINGTON BLVD E,00131,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
5286,4273893024,2015-12-30T00:00:00,1403.0,WP8204,NaN,TN,201604.0,NaN,HYUN,PA,CO,20 WASHINGTON BLVD E,00131,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
9708,4273301594,2015-12-31T00:00:00,1431.0,WP8204,NaN,NV,201604.0,NaN,TOYT,PA,WT,20 WASHINGTON BLVD E,00131,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
13369,4274122274,2015-12-31T00:00:00,1225.0,WP8204,NaN,CA,201604.0,NaN,TOYT,PA,SL,20 WASHINGTON BLVD E,00308,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
13373,4274122311,2015-12-31T00:00:00,1449.0,WP8204,NaN,CA,201602.0,NaN,TOYT,PA,BK,22 WASHINGTON BLVD E,00308,51.0,88.13B+,METER EXP.,63.0,6420276.9,1815183.6
26495,4274714220,2016-01-04T00:00:00,1042.0,WP8204,NaN,MT,201601.0,NaN,HYUN,PA,GY,20 WASHINGTON BLVD E,00164,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
30811,4274125634,2016-01-05T00:00:00,1732.0,WP8204,NaN,CA,201601.0,NaN,OTHR,MC,BK,22 WASHINGTON BLVD E,00308,51.0,88.13B+,METER EXP.,63.0,6420276.9,1815183.6
47360,4274629015,2016-01-07T00:00:00,1318.0,WP8204,NaN,CA,201604.0,NaN,HOND,PA,PR,20 WASHINGTON BLVD E,00331,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
47362,4274629030,2016-01-07T00:00:00,1322.0,WP8204,NaN,CA,201605.0,NaN,MERZ,PA,BL,20 WASHINGTON BLVD E,00331,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
48075,4274788140,2016-01-07T00:00:00,1133.0,WP8204,NaN,CA,201610.0,NaN,NISS,PA,SL,20 WASHINGTON BLVD E,00111,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
48082,4274788210,2016-01-07T00:00:00,1247.0,WP8204,NaN,CO,201612.0,NaN,NISS,PA,SL,16 WASHINGTON BLVD E,00111,51.0,88.13B+,METER EXP.,63.0,6420259.5,1815171.6
48086,4274788254,2016-01-07T00:00:00,1358.0,WP8204,NaN,CA,201606.0,NaN,DODG,PA,SL,22 WASHINGTON BLVD E,00111,51.0,88.13B+,METER EXP.,63.0,6420276.9,1815183.6
48093,4274788324,2016-01-07T00:00:00,1742.0,WP8204,NaN,CA,201609.0,NaN,BMW,PA,BK,16 WASHINGTON BLVD E,00111,51.0,88.13B+,METER EXP.,63.0,6420259.5,1815171.6
48094,4274788335,2016-01-07T00:00:00,1744.0,WP8204,NaN,CA,201601.0,NaN,JEEP,PA,SL,14 WASHINGTON BLVD E,00111,51.0,88.13B+,METER EXP.,63.0,6420253.7,1815167.7
51325,4273897880,2016-01-08T00:00:00,1056.0,WP8204,NaN,CA,NaN,NaN,FORD,PA,BK,20 WASHINGTON BLVD E,00136,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
51673,4273987745,2016-01-08T00:00:00,816.0,WP8204,NaN,CA,NaN,NaN,MAZD,PA,BK,20 WASHINGTON BLVD E,00131,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
51698,4273987992,2016-01-08T00:00:00,1437.0,WP8204,NaN,CA,201604.0,NaN,FORD,PU,WT,20 WASHINGTON BLVD E,00131,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
55039,4274663352,2016-01-08T00:00:00,1213.0,WP8204,NaN,AZ,201702.0,NaN,CHEV,PA,WT,16 WASHINGTON BLVD E,00308,51.0,88.13B+,METER EXP.,63.0,6420259.5,1815171.6
57407,4273875675,2016-01-10T00:00:00,1235.0,WP8204,NaN,CA,201608.0,NaN,MERZ,PA,GY,20 WASHINGTON BLVD E,00136,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
57410,4273875701,2016-01-10T00:00:00,1335.0,WP8204,NaN,CA,201609.0,NaN,SUBA,PA,GN,20 WASHINGTON BLVD E,00136,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
57412,4273875723,2016-01-10T00:00:00,1343.0,WP8204,NaN,FL,201609.0,NaN,HD,MC,GN,20 WASHINGTON BLVD E,00136,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
57413,4273875734,2016-01-10T00:00:00,1443.0,WP8204,NaN,CA,201607.0,NaN,BMW,PA,BK,20 WASHINGTON BLVD E,00136,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
57416,4273875760,2016-01-10T00:00:00,1508.0,WP8204,NaN,CA,201607.0,NaN,TOYT,PA,WT,20 WASHINGTON BLVD E,00136,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6
60875,4273465744,2016-01-11T00:00:00,1210.0,WP8204,NaN,CA,201612.0,NaN,TOYT,PA,BK,20 WASHINGTON BLVD E,00131,51.0,88.13B+,METER EXP.,63.0,6420271.1,1815179.6

In [20]:
subsetMeter_df['Location'].value_counts()

20 WASHINGTON BLVD E    2578
16 WASHINGTON BLVD E      96
22 WASHINGTON BLVD E      57
14 WASHINGTON BLVD E      34
15 WASHINGTON BLVD E       1
18 WASHINGTON BLVD E       1
23 WASHINGTON BLVD E       1
Name: Location, dtype: int64

In [22]:
subsetMeter_df['Make'].value_counts()

TOYT    386
FORD    296
CHEV    244
NISS    230
HOND    180
HYUN    146
JEEP    117
DODG    116
VOLK    113
MERZ    112
BMW     102
KIA      86
CHRY     67
AUDI     66
MAZD     53
LEXS     51
GMC      35
INFI     34
SUBA     32
HD       26
CADI     26
VOLV     25
MITS     20
MNNI     20
LNDR     18
LINC     16
RROV     14
BUIC     14
PORS     14
ACUR     12
FIAT     10
UNK       9
PONT      9
OTHR      8
JAGU      8
MERC      7
TSMR      6
SUZI      5
ISU       5
OLDS      5
KAWK      4
YAMA      4
MASE      4
STRN      4
SAA       2
GEO       1
HUMM      1
STLG      1
SMRT      1
CHEC      1
IND       1
FERR      1
Name: Make, dtype: int64

In [23]:
subsetMeter_df['Color'].value_counts()

BK    671
WT    550
GY    528
SL    408
BL    222
RD    205
GN     42
MR     36
GO     33
YE     16
TN     13
BN     12
BG      9
OT      7
OR      6
PR      4
CO      3
UN      2
PK      1
Name: Color, dtype: int64

In [25]:
##- Subset by Agency
subsetHollywood_df = citations.loc[(citations["Agency"] == 4), :]

subsetHollywood_df.head(20)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
18603,1109077314,2015-12-16T00:00:00,1731.0,NaN,NaN,CA,201608.0,NaN,FORD,PA,BK,PECAN GROVE/ZOO DR,NaN,4.0,8603,PK IN PROH AREA,68.0,99999.0,99999.0
18604,1109077325,2015-12-16T00:00:00,1735.0,NaN,NaN,CA,201603.0,NaN,NISS,PA,BK,5400 ZOO DR,NaN,4.0,8603,PK IN PROH AREA,68.0,6472743.1,1878859.9
18605,1109077336,2015-12-18T00:00:00,1728.0,NaN,NaN,CA,201606.0,NaN,BMW,PA,WH,5400 ZOO DR,NaN,4.0,8603,PK IN PROH AREA,68.0,6472743.1,1878859.9
18606,1109077340,2015-12-18T00:00:00,1731.0,NaN,NaN,CA,201602.0,NaN,HOND,PA,BK,5400 ZOO DR,NaN,4.0,8603,PK IN PROH AREA,68.0,6472743.1,1878859.9
18607,1109077351,2015-12-18T00:00:00,1738.0,NaN,NaN,CA,NaN,NaN,NISS,PA,WH,5200 ZOO DR,NaN,4.0,8603,PK IN PROH AREA,68.0,6475437.7,1876790.7
18608,1109078633,2015-12-15T00:00:00,1806.0,NaN,NaN,CA,201604.0,NaN,VOLK,PA,GY,11800 FOOTHILL BLVD,NaN,4.0,6344K2,NO PK BET 1-3AM,68.0,6442697.5,1922160.1
18609,1109078644,2015-12-17T00:00:00,1812.0,NaN,NaN,CA,201610.0,NaN,LEXU,PA,GY,11800 FOOTHILL BLVD,NaN,4.0,6344K2,NO PK BET 1-3AM,68.0,6442697.5,1922160.1
18610,1109078655,2015-12-17T00:00:00,1809.0,NaN,NaN,CA,201506.0,NaN,HOND,PA,SI,11800 FOOTHILL BLVD,NaN,4.0,6344K2,NO PK BET 1-3AM,68.0,6442697.5,1922160.1
18611,1109078666,2015-12-17T00:00:00,1810.0,NaN,NaN,CA,201606.0,NaN,MAZD,PA,BK,11800 FOOTHILL BLVD,NaN,4.0,6344K2,NO PK BET 1-3AM,68.0,6442697.5,1922160.1
18612,1109078670,2015-12-17T00:00:00,1830.0,NaN,NaN,CA,201608.0,NaN,UNK,PA,GY,11800 FOOTHILL BLVD,NaN,4.0,6344K2,NO PK BET 1-3AM,68.0,6442697.5,1922160.1
18613,1109079635,2015-12-13T00:00:00,1649.0,NaN,NaN,CA,201601.0,NaN,CHEV,TR,GY,11770 FOOTHILL BLVD,NaN,4.0,013,22500H,68.0,6443160.7,1921957.7
18614,1109080125,2015-12-17T00:00:00,1326.0,NaN,NaN,CA,201607.0,NaN,JEEP,PA,GY,2800 E OBS RD/W OBS,NaN,4.0,8049,WRG SD/NOT PRL,63.0,99999.0,99999.0
18615,1109080136,2015-12-17T00:00:00,1549.0,NaN,NaN,IL,201601.0,NaN,VOLK,PA,BK,2800 E OBS RD/W OBS,NaN,4.0,8056E4,RED ZONE,93.0,99999.0,99999.0
18616,1109080151,2015-12-17T00:00:00,1619.0,NaN,NaN,CA,201604.0,NaN,AUDI,PA,GY,2800 E OBS RD/OBS LT,NaN,4.0,6344K7,PK OUTSD PK STL,58.0,99999.0,99999.0
18617,1109080162,2015-12-17T00:00:00,1626.0,NaN,NaN,CA,201610.0,NaN,JEEP,PA,SI,2800 E OBS RD/W OBS,NaN,4.0,000,NaN,NaN,99999.0,99999.0
18618,1109080173,2015-12-18T00:00:00,2108.0,NaN,NaN,CA,201609.0,NaN,BMW,PA,SI,2800 E OBS RD/OBS LT,NaN,4.0,225078A,HANDICAP/NO DP ID,363.0,99999.0,99999.0
18619,1109080184,2015-12-18T00:00:00,2112.0,NaN,NaN,CA,201602.0,NaN,LINC,PA,BK,2800 E OBS RD/OBS LT,NaN,4.0,8056E4,RED ZONE,93.0,99999.0,99999.0
18620,1109080195,2015-12-18T00:00:00,2148.0,NaN,NaN,CA,201306.0,NaN,GMC,PA,RE,2800 E OBS RD/OBS LT,NaN,4.0,8056E4,RED ZONE,93.0,99999.0,99999.0
18621,1109081422,2015-12-18T00:00:00,15.0,NaN,NaN,CA,201512.0,NaN,BMW,PA,SI,WESTEN CYN RD,NaN,4.0,8603,PK IN PROH AREA,68.0,99999.0,99999.0
18622,1109085574,2015-09-11T00:00:00,1755.0,NaN,NaN,CA,201603.0,NaN,JEEP,PA,BL,2800 E OBSERVATORY,NaN,4.0,8056E4,RED ZONE,93.0,6470141.4,1867430.4

In [26]:
subsetHollywood_df.shape

(28309, 19)

In [28]:
#-- Determine any Meters for Hollywood
violationCodeSubsetHollywood_df = subsetHollywood_df.loc[(subsetHollywood_df["Violation code"] == '88.13B+'), :]

violationCodeSubsetHollywood_df.head(20)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
6343150,4307014250,2017-11-06T00:00:00,1418.0,80111,NaN,CA,201810.0,NaN,BMW,PA,BK,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6343151,4307020303,2017-11-21T00:00:00,1533.0,80101,NaN,CA,201708.0,NaN,NISS,PA,WT,1235 FIGUEROA PL,101,4.0,88.13B+,METER EXP.,63.0,6.476265e+06,1.743317e+06
6343152,4307020314,2017-11-21T00:00:00,1536.0,80101,NaN,CA,201811.0,NaN,KIA,PA,SL,1235 FIGUEROA PL,101,4.0,88.13B+,METER EXP.,63.0,6.476265e+06,1.743317e+06
6343153,4307020325,2017-11-21T00:00:00,1539.0,80101,NaN,CA,NaN,NaN,HOND,PA,WT,1235 FIGUEROA PL,101,4.0,88.13B+,METER EXP.,63.0,6.476265e+06,1.743317e+06
6343546,4313006213,2017-11-12T00:00:00,1238.0,80111,NaN,CA,201807.0,NaN,CHEV,PA,BK,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511446,4307014294,2017-12-08T00:00:00,1305.0,80101,NaN,CA,201804.0,NaN,FORD,PA,GN,1235 FIGUEROA PL,101,4.0,88.13B+,METER EXP.,63.0,6.476265e+06,1.743317e+06
6511447,4307014305,2017-12-08T00:00:00,1313.0,80101,NaN,CA,201807.0,NaN,CHEV,PA,WT,1235 FIGUEROA PL,101,4.0,88.13B+,METER EXP.,63.0,6.476265e+06,1.743317e+06
6511452,4307014386,2017-12-28T00:00:00,1456.0,80111,NaN,CA,201810.0,NaN,TOYT,VN,BG,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511453,4307014390,2017-12-28T00:00:00,1512.0,80111,NaN,VA,201810.0,NaN,KIA,PA,GY,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511462,4307020410,2017-12-21T00:00:00,1457.0,90117,NaN,CA,201806.0,NaN,FORD,PU,WT,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511463,4307020421,2017-12-21T00:00:00,1504.0,90117,NaN,CA,201810.0,NaN,DODG,PA,RD,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511464,4307020432,2017-12-21T00:00:00,1507.0,90117,NaN,CA,201801.0,NaN,JEEP,PA,RD,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511465,4307020443,2017-12-21T00:00:00,1530.0,80117,NaN,CA,201810.0,NaN,FORD,PA,GY,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511466,4307020465,2017-12-21T00:00:00,1541.0,80117,NaN,CA,201809.0,NaN,DODG,PA,GY,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511467,4307020480,2017-12-22T00:00:00,1403.0,90110,NaN,CA,201807.0,NaN,HOND,PA,SL,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511468,4307020491,2017-12-22T00:00:00,1413.0,80112,NaN,CA,201811.0,NaN,FORD,PA,WT,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511469,4313006250,2017-12-06T00:00:00,1354.0,90110,NaN,CA,201805.0,NaN,TOYT,PA,WT,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511470,4313006261,2017-12-06T00:00:00,1627.0,90110,NaN,CA,201803.0,NaN,HOND,PA,WT,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6511471,4313006272,2017-12-06T00:00:00,1630.0,90110,NaN,CA,201811.0,NaN,TOYT,PA,YE,3720 S STEPHEN M WHITE DR,101,4.0,88.13B+,METER EXP.,63.0,6.474665e+06,1.717173e+06
6694574,4307014412,2018-01-04T00:00:00,1331.0,80106,NaN,CA,201801.0,NaN,TOYT,PA,RD,1235 FIGUEROA PL,101,4.0,88.13B+,METER EXP.,63.0,6.476265e+06,1.743317e+06

In [29]:
violationCodeSubsetHollywood_df.shape

(78, 19)

In [30]:
#-- Explorer Other Agencies
subsetWestern_df = citations.loc[(citations["Agency"] == 51), :]

subsetWestern_df.head()

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
329,1113879756,2015-12-24T00:00:00,1836.0,NaN,NaN,CA,201609.0,NaN,LEXU,PA,GY,11040 W PICO BLVD,00123,51.0,8070,PARK IN GRID LOCK ZN,163.0,6430292.7,1836375.2
330,1113879760,2015-12-24T00:00:00,1844.0,NaN,NaN,CA,201606.0,NaN,LEXU,PA,GY,10974 W PICO BLVD,00123,51.0,8070,PARK IN GRID LOCK ZN,163.0,6430871.9,1836702.5
331,1113879771,2015-12-24T00:00:00,1848.0,NaN,NaN,CA,201604.0,NaN,TOYO,PA,GY,2380 S WESTWOOD BLVD,00123,51.0,8069AP,NO STOP/STAND PM,93.0,6431745.3,1837410.7
332,1113879782,2015-12-24T00:00:00,1849.0,NaN,NaN,CA,201604.0,NaN,TOYO,PA,BK,2380 WESTWOOD BLVD,00123,51.0,8069AP,NO STOP/STAND PM,93.0,6431745.3,1837410.7
333,1113879793,2015-12-24T00:00:00,1850.0,NaN,NaN,CA,201610.0,NaN,LINC,PA,BK,2370 S WESTWOOD,00123,51.0,8069AP,NO STOP/STAND PM,93.0,6431684.9,1837495.6

In [31]:
subsetWestern_df.shape

(2081757, 19)

In [32]:
violationCodeSubsetWestern_df = subsetWestern_df.loc[(subsetWestern_df["Violation code"] == '88.13B+'), :]

violationCodeSubsetWestern_df.head(20)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
669,4271978745,2015-12-30T00:00:00,1108.0,V6127,NaN,CA,201610.0,NaN,FORD,PA,WT,29 WINDWARD AVE E,00111,51.0,88.13B+,METER EXP.,63.0,6418243.5,1818046.6
670,4271978756,2015-12-30T00:00:00,1116.0,V27610,NaN,CA,201602.0,NaN,JEEP,PA,MR,1608 PACIFIC AVE S,00111,51.0,88.13B+,METER EXP.,63.0,6418525.8,1818220.6
671,4271978760,2015-12-30T00:00:00,1122.0,V117,NaN,CA,201603.0,NaN,CHEC,TK,OT,1300 MAIN ST,00111,51.0,88.13B+,METER EXP.,63.0,6418478.2,1818975.3
672,4271978771,2015-12-30T00:00:00,1131.0,V27610,NaN,CA,201611.0,NaN,JEEP,PA,RD,1608 PACIFIC AVE S,00111,51.0,88.13B+,METER EXP.,63.0,6418525.8,1818220.6
673,4271978793,2015-12-30T00:00:00,1140.0,V6125,NaN,CA,201607.0,NaN,TOYT,PA,WT,61 WINDWARD AVE E,00111,51.0,88.13B+,METER EXP.,63.0,6418361.5,1818132.4
674,4271978804,2015-12-30T00:00:00,1151.0,V74,NaN,CA,201607.0,NaN,BMW,PA,BL,100 VENICE WAY,00111,51.0,88.13B+,METER EXP.,63.0,6418576.8,1818157.1
676,4271978826,2015-12-30T00:00:00,1154.0,V102,NaN,PA,201603.0,NaN,BMW,PA,WT,1700 MAIN ST,00111,51.0,88.13B+,METER EXP.,63.0,6418937.4,1818226.5
677,4271978830,2015-12-30T00:00:00,1159.0,V6123,NaN,CA,NaN,NaN,KIA,PA,SL,121 WINDWARD AVE E,00111,51.0,88.13B+,METER EXP.,63.0,6418613.3,1818315.2
678,4271978841,2015-12-30T00:00:00,1207.0,V166,NaN,AZ,NaN,NaN,JEEP,TK,WT,1401 MAIN ST,00111,51.0,88.13B+,METER EXP.,63.0,6418563.1,1818845.7
680,4271978863,2015-12-30T00:00:00,1231.0,V212,NaN,CA,201606.0,NaN,CHRY,PA,WT,1500 PARK ROW,00111,51.0,88.13B+,METER EXP.,63.0,6418469.1,1818535.4
681,4271978874,2015-12-30T00:00:00,1232.0,V207,NaN,CA,201612.0,NaN,FIAT,PA,SL,1500 PARK ROW,00111,51.0,88.13B+,METER EXP.,63.0,6418469.1,1818535.4
682,4271978885,2015-12-30T00:00:00,1235.0,V27610,NaN,CA,201602.0,NaN,AUDI,PA,BK,1608 PACIFIC AVE S,00111,51.0,88.13B+,METER EXP.,63.0,6418525.8,1818220.6
683,4271978896,2015-12-30T00:00:00,1237.0,V27610,NaN,CA,201609.0,NaN,VOLK,PA,OT,1608 PACIFIC AVE S,00111,51.0,88.13B+,METER EXP.,63.0,6418525.8,1818220.6
684,4271978900,2015-12-30T00:00:00,1242.0,V6126,NaN,IL,201610.0,NaN,KIA,PA,WT,54 WINDWARD AVE E,00111,51.0,88.13B+,METER EXP.,63.0,6418335.2,1818113.3
685,4271978911,2015-12-30T00:00:00,1244.0,V6128,NaN,CA,201608.0,NaN,CHEV,PA,SL,70 WINDWARD AVE E,00111,51.0,88.13B+,METER EXP.,63.0,6418395.8,1818157.3
691,4271978970,2015-12-30T00:00:00,1303.0,V27610,NaN,CA,201602.0,NaN,FORD,TK,GN,1608 PACIFIC AVE S,00111,51.0,88.13B+,METER EXP.,63.0,6418525.8,1818220.6
693,4271978992,2015-12-30T00:00:00,1353.0,V111,NaN,WA,201606.0,NaN,DODG,PA,GY,1400 MAIN ST,00111,51.0,88.13B+,METER EXP.,63.0,6418563.1,1818845.7
694,4271979003,2015-12-30T00:00:00,1358.0,V74,NaN,CA,201608.0,NaN,TOYT,PA,BK,100 VENICE WAY,00111,51.0,88.13B+,METER EXP.,63.0,6418576.8,1818157.1
712,4272009906,2015-12-30T00:00:00,1630.0,PW442,NaN,CA,201606.0,NaN,NISS,PA,BL,2300 COTNER AV,00115,51.0,88.13B+,METER EXP.,63.0,6428945.7,1836442.5
713,4272009910,2015-12-30T00:00:00,1641.0,OS164,NaN,CA,201604.0,NaN,TOYT,PA,BL,2200 CORINTH AV,00115,51.0,88.13B+,METER EXP.,63.0,6427692.6,1836366.8

In [33]:
violationCodeSubsetWestern_df.shape

(404697, 19)